---
# tasks file for send_log
- name: Debugging
  debug:
    var: database_username
    
- name: Gera arquivo de log
  blockinfile:
    path: /home/ansible/relatorio
    create: yes
    block: |
      Nome do servidor: {{ resultado_name }}
      Endere√ßo IPV4: {{ resultado_address }}
      Resposta de Ping: {{ resultado }}
